[2016Oct13 14:47:10,562][INFO ][04125342996_1476386217976][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342996_1476386217976, OldTarget=crear.suscriptor.rtbs, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734024020500016, reportedFrom=CCWS, FECHA=2016-10-13 14:46:57, sistema=rtbs, profile=08, PUK=15045492, PUK2=60525523, proceso=preactivacion, GSM=04125342996, PIN1=1108, ERROR=, ICCID=8958021306050000220F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=, ID=04125342996_1476386217976}}]
[2016Oct13 14:47:10,564][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342997_1476386218008, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734024020500017, reportedFrom=CCWS, FECHA=2016-10-13 14:46:58, sistema=rtbs, profile=08, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342997, PIN1=6440, ERROR=0, ICCID=8958021306050000238F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Cliente creado con exito en RTBS, ID=04125342997_1476386218008}}]
[2016Oct13 14:47:10,583][ERROR][04125342996_1476386217976][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 14:47:10,583][ERROR][04125342997_1476386218008][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 14:47:10,599][INFO ][04125342996_1476386217976][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 14:47:10,599][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 14:47:10,831][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342997_1476386218008, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734024020500017, reportedFrom=HLR_WS, FECHA=2016-10-13 14:46:58, sistema=rtbs, profile=08, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342997, PIN1=6440, ERROR=0, ICCID=8958021306050000238F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Request accepted, ID=04125342997_1476386218008}}]
[2016Oct13 14:47:10,906][ERROR][04125342997_1476386218008][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 14:47:10,909][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 14:47:16,815][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342997_1476386218008, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734024020500017, reportedFrom=HLR, FECHA=2016-10-13 14:46:58, sistema=rtbs, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342997, PIN1=6440, ERROR=0, ICCID=8958021306050000238F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=All tasks are successfully executed, ID=04125342997_1476386218008}}]
[2016Oct13 14:47:16,833][ERROR][04125342997_1476386218008][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 14:47:16,836][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 14:51:13,336][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342997_1476386218008, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734024020500017, reportedFrom=IVR, FECHA=2016-10-13 14:46:58, sistema=rtbs, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342997, PIN1=6440, ERROR=09, ICCID=8958021306050000238F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Error ocurrido durante el registro del suscriptor en IVR, ID=04125342997_1476386218008}}]
[2016Oct13 14:51:13,354][ERROR][04125342997_1476386218008][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 14:51:13,357][INFO ][04125342997_1476386218008][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:45,576][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342998_1476388179808, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734021018988043, reportedFrom=CCWS, FECHA=2016-10-13 15:19:39, sistema=rtbs, profile=08, PUK=15045492, PUK2=60525523, proceso=preactivacion, GSM=04125342998, PIN1=1108, ERROR=0, ICCID=8958020708280956207F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Cliente creado con exito en RTBS, ID=04125342998_1476388179808}}]
[2016Oct13 15:19:45,601][ERROR][04125342998_1476388179808][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:45,605][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:45,685][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342998_1476388179808, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734021018988043, reportedFrom=HLR_WS, FECHA=2016-10-13 15:19:39, sistema=rtbs, profile=08, PUK=15045492, PUK2=60525523, proceso=preactivacion, GSM=04125342998, PIN1=1108, ERROR=0, ICCID=8958020708280956207F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Request accepted, ID=04125342998_1476388179808}}]
[2016Oct13 15:19:45,703][ERROR][04125342998_1476388179808][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:45,706][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:45,849][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342999_1476388179809, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734021018988044, reportedFrom=CCWS, FECHA=2016-10-13 15:19:39, sistema=rtbs, profile=08, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342999, PIN1=6440, ERROR=0, ICCID=8958020708280956215F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Cliente creado con exito en RTBS, ID=04125342999_1476388179809}}]
[2016Oct13 15:19:45,867][ERROR][04125342999_1476388179809][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:45,870][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:46,052][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342999_1476388179809, OldTarget=crear.suscriptor.rtbs, Target=aprovisionar.suscriptor.hlr} | context: {PIN=0000, IMSI=734021018988044, reportedFrom=HLR_WS, FECHA=2016-10-13 15:19:39, sistema=rtbs, profile=08, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342999, PIN1=6440, ERROR=0, ICCID=8958020708280956215F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Request accepted, ID=04125342999_1476388179809}}]
[2016Oct13 15:19:46,070][ERROR][04125342999_1476388179809][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:46,073][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:49,037][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342999_1476388179809, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734021018988044, reportedFrom=HLR, FECHA=2016-10-13 15:19:39, sistema=rtbs, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342999, PIN1=6440, ERROR=0, ICCID=8958020708280956215F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=All tasks are successfully executed, ID=04125342999_1476388179809}}]
[2016Oct13 15:19:49,054][ERROR][04125342999_1476388179809][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:49,057][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:19:50,474][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342998_1476388179808, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734021018988043, reportedFrom=HLR, FECHA=2016-10-13 15:19:39, sistema=rtbs, PUK=15045492, PUK2=60525523, proceso=preactivacion, GSM=04125342998, PIN1=1108, ERROR=0, ICCID=8958020708280956207F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=All tasks are successfully executed, ID=04125342998_1476388179808}}]
[2016Oct13 15:19:50,491][ERROR][04125342998_1476388179808][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:19:50,494][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:32:33,349][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342999_1476388179809, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734021018988044, reportedFrom=IVR, FECHA=2016-10-13 15:19:39, sistema=rtbs, PUK=22654004, PUK2=15107261, proceso=preactivacion, GSM=04125342999, PIN1=6440, ERROR=09, ICCID=8958020708280956215F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Error ocurrido durante el registro del suscriptor en IVR, ID=04125342999_1476388179809}}]
[2016Oct13 15:32:33,366][ERROR][04125342999_1476388179809][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:32:33,370][INFO ][04125342999_1476388179809][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
[2016Oct13 15:32:34,759][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:126][Mensaje recibido con exito en la cola de SOLICITUD ve.com.digitel.premasivas.model.Request{ | header: {traceid=04125342998_1476388179808, OldTarget=registrar.suscriptor.ivr, Target=generar.archivo.salida} | context: {PIN=0000, IMSI=734021018988043, reportedFrom=IVR, FECHA=2016-10-13 15:19:39, sistema=rtbs, PUK=15045492, PUK2=60525523, proceso=preactivacion, GSM=04125342998, PIN1=1108, ERROR=09, ICCID=8958020708280956207F, NOMARCHIVO=DIG05028_1_OCCIDENTE_2, ERROR_MSG=Error ocurrido durante el registro del suscriptor en IVR, ID=04125342998_1476388179808}}]
[2016Oct13 15:32:34,777][ERROR][04125342998_1476388179808][processRequest RCController.java:83][Codigo de Error: SRE001-EM03 Mensaje de Error: No se puede tomar solicitud de la cola]
javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc [Root exception is javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc]; remaining name 'datasource/res'
	at weblogic.rjvm.BasicOutboundRequest.sendReceive(BasicOutboundRequest.java:108)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:290)
	at weblogic.rmi.cluster.ReplicaAwareRemoteRef.invoke(ReplicaAwareRemoteRef.java:248)
	at weblogic.jndi.internal.ServerNamingNode_815_WLStub.lookup(Unknown Source)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:375)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:363)
	at javax.naming.InitialContext.lookup(InitialContext.java:347)
	at ve.com.digitel.res.rc.RESDelegator.execute(RESDelegator.java:129)
	at ve.com.digitel.res.rc.RCHelper.processRequest(RCHelper.java:77)
	at ve.com.digitel.res.rc.RCController.processRequest(RCController.java:76)
	at ve.com.digitel.res.ejb.RegisterElementMDBean.onMessage(RegisterElementMDBean.java:128)
	at weblogic.ejb20.internal.MDListener.execute(MDListener.java:400)
	at weblogic.ejb20.internal.MDListener.transactionalOnMessage(MDListener.java:333)
	at weblogic.ejb20.internal.MDListener.onMessage(MDListener.java:298)
	at weblogic.jms.client.JMSSession.onMessage(JMSSession.java:2686)
	at weblogic.jms.client.JMSSession.execute(JMSSession.java:2598)
	at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:224)
	at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:183)
Caused by: javax.naming.NameNotFoundException: While trying to lookup 'jdbc.datasource.res' didn't find subcontext 'datasource' Resolved jdbc
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:924)
	at weblogic.jndi.internal.BasicNamingNode.lookupHere(BasicNamingNode.java:225)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:154)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:188)
	at weblogic.jndi.internal.BasicNamingNode.lookup(BasicNamingNode.java:196)
	at weblogic.jndi.internal.RootNamingNode_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:492)
	at weblogic.rmi.cluster.ReplicaAwareServerRef.invoke(ReplicaAwareServerRef.java:108)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:435)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:147)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:430)
	at weblogic.rmi.internal.BasicExecuteRequest.execute(BasicExecuteRequest.java:35)
	... 2 more
[2016Oct13 15:32:34,781][INFO ][04125342998_1476388179808][onMessage RegisterElementMDBean.java:130][Solicitud procesada <?xml version="1.0" encoding="UTF-8"?>
<Response
  xmlns="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://digitel.com.ve/eai/BusinessIntegration/SRE/SRE001.xsd">
  <traceId></traceId>
  <OperationMessages>
    <OperationMessage>
      <code>SRE001-EM01</code>
      <message>No se puede tomar solicitud de la cola</message>
    </OperationMessage>
  </OperationMessages>
</Response>]
